# Header
menu:
  主页: /blog
  归档: /blog/archives
  关于我: /blog/about

# SubNav
subnav:
  github: "https://github.com/ChaosLeong"
  # weibo: "http://weibo.com/lgfsise"
  #zhihu: "#"
  #douban: "#"
  mail: "mailto:lgf42031@gmail.com"
  #facebook: "#"
  google: "https://plus.google.com/u/0/+ChaosGLeong"
  #twitter: "#"
  #linkedin: "#"
  rss: "/blog/atom.xml"

root: /blog/

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: false

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /img/favicon.ico

#你的头像url
avatar: /img/favicon.png
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: chaosleong
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
friends: false
#开启——
# friends:
#   奥巴马的博客: http://localhost:4000/
#   卡卡的美丽传说: http://localhost:4000/
#   本泽马的博客: http://localhost:4000/
#   吉格斯的博客: http://localhost:4000/
#   习大大大不同: http://localhost:4000/
#   托蒂的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
aboutme: false
#开启——
#aboutme: 90 后 Android 程序猿，目前就职于广州 GlassX